### ISSUE TITLE
move dashboard drawing to README

### ISSUE THREAD

**Issue by charlesfrye** [TeddyFrye/dashboard#1]
![image](https://github.com/TeddyFrye/dashboard/assets/10442975/e86882e6-5047-4bf2-85ad-6ca8196e963f).

**Comment by charlesfrye** [comment]
raw:
`![image](https://github.com/TeddyFrye/dashboard/assets/10442975/e86882e6-5047-4bf2-85ad-6ca8196e963f)`

**Comment by Sally-Frye** [comment]
Closed with commit 658f18d
